
```{r setup}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../maps/", fig.width = 3.5, fig.height = 4.2)
source("../scripts/99_utils.R")
```

```{r james_river_mo}

coords <- get_coords("James River (Missouri)")
pnt <- st_as_sf(coords, coords = c("lon", "lat"), crs = 4326)
# mapview(pnt)

qry <- nhd_plus_query(coords$lon, coords$lat,
  dsn = c("NHDFlowLine"),
  buffer_dist = units::as_units(0.2, "km"))

# mapview(qry$sp$NHDFlowLine) + mapview(pnt)

nldi_feature <- list(featureSource = "comid",
  featureID = qry$sp$NHDFlowLine$COMID)
flowline <- get_nldi_feature(nldi_feature = nldi_feature)
stream_up     <- nhdplusTools::navigate_nldi(nldi_feature,
  mode = "UM", distance_km = 320)
# stream_down     <- nhdplusTools::navigate_nldi(nldi_feature,
#   mode = "DM", distance_km = 4)
basin         <- get_nldi_basin(nldi_feature = nldi_feature)

eromflow  <- nhd_plus_load(find_vpu(basin), "EROMExtension", "EROM_MA0001") %>%
  dplyr::filter(ComID %in% stream_up$UM_flowlines$nhdplus_comid) %>%
  dplyr::select(ComID, Q0001F) %>%
  dplyr::mutate(ComID = as.character(ComID))
stream_up$UM_flowlines <- dplyr::left_join(stream_up$UM_flowlines, eromflow,
  by = c("nhdplus_comid" = "ComID"))

states_sf <- sf::st_make_valid(sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE)))
county_sf <- sf::st_make_valid(sf::st_as_sf(maps::map("county", plot = FALSE, fill = TRUE)))

bbox <- st_as_sf(st_buffer(basin, 6))
bbox_zoom <- st_buffer(bbox, -3.4)

states <- states_sf[
  unlist(lapply(st_intersects(states_sf, bbox), function(x) length(x) > 0)), ]
counties <- county_sf[
  unlist(lapply(st_within(county_sf, states), function(x) length(x) > 0)), ]

# mapview(basin) + mapview(pnt) + mapview(stream_up) + mapview(bbox_zoom) #  + mapview(stream_down)

# "antiquewhite"
# "lightgoldenrodyellow"

test <- stream_up$UM_flowlines$Q0001F
range(test)


ggplot() +
  geom_sf(data = states, fill = "#f7d4ab", color = alpha("black", 0.8)) +
  geom_sf(data = basin, fill = "#ffffd1", color = alpha("white", 0)) +
  geom_sf(data = counties, fill = alpha("white", 0),
    color = alpha("black", 0.1)) +
  geom_sf(data = stream_up$UM_flowlines, color = "dodgerblue3",
    size = scales::rescale(stream_up$UM_flowlines$Q0001F, c(0.8, 1.6))) +
  geom_sf(data = st_as_sfc(st_bbox(bbox_zoom)), fill = alpha("white", 0)) +
  coord_sf(
    xlim = sf::st_bbox(bbox_zoom)[c(1, 3)],
    ylim = sf::st_bbox(bbox_zoom)[c(2, 4)],
    expand = FALSE
  ) +
  geom_sf_text(data = stream_up$UM_flowlines[
    ceiling(nrow(stream_up$UM_flowlines) / 2), ],
  aes(label = "James River (Missouri)"),
  nudge_y = 0.3, nudge_x = 0.6, size = 3) +
  theme(axis.title = element_blank())
```